/*                                                 FLASHBACK DROP TABLE
Usted puede utilizar Flashback Drop Table, para restaurar una tabla eliminada por error humano. 
Para ello hace uso de las funcionalidades de la Papelera de Reciclaje.
--- 1. ACTIVE LA PAPELERA DE RECICLAJE  */

ALTER SESSION SET RECYCLEBIN=ON;


--- 2. CONSULTE LA PAPELERA DE RECICLAJE
SELECT * FROM RECYCLEBIN;

--- 3. CREAR EL USUARIO “ACADEMICO” 

CREATE USER ACADEMICO IDENTIFIED BY "123"
DEFAULT TABLESPACE USERS
QUOTA UNLIMITED ON USERS:

GRANT DBA TO ACADEMICO;

 --- 4. CONECTARSE COMO ACADEMICO Y CREAR LA TABLA NOTAS

CREATE TABLE NOTAS ( ID INTEGER , N1 INTEGER , N2 INTEGER) ;
INSERT INTO NOTAS VALUES ( 1 , 12 , 15 );
INSERT INTO NOTAS VALUES ( 2 , 18 , 14 );
INSERT INTO NOTAS VALUES ( 3 , 12 , 12 );

COMMIT;

SELECT * FROM NOTAS;

--- 5. ELIMINAR LA TABLA

DROP TABLE NOTAS;

--- 6. CONSULTAR LA PAPELERA DE RECICLAJE

SELECT * FROM RECYCLEBIN;

--	Puede visualizar las tablas dropeadas con nuevo nombre..!!!!

--- 7. CONSULTAR LA TABLA DROPEADA

SELECT * FROM "BIN$JaGxm8FWRCGKBa5kN/9ZkQ==$0"

--- 8. RECUPERAR LA TABLA DROPEADA

FLASHBACK TABLE NOTAS TO BEFORE DROP;

SELECT * FROM NOTAS;

--	Tabla recuperada…!!!!!
--SI TRABAJASTE CON SYS O SYSTEM, LA TABLA FUE BORRADA DEFINITIVAMENTE

-- PARAMETRO DE RETENCION DE DATOS EN FLASBACK


--- 9. DESACTIVAR LA PAPELERA DE RECICLAJE

ALTER SESSION SET RECYCLEBIN=OFF;

--- 10. CREAR UNA NUEVA TABLA 

CREATE TABLE NOTAS_NEW AS SELECT * FROM NOTAS

SELECT * FROM NOTAS_NEW;

--- 11. ELIMINAR LA TABLA NOTAS_NEW Y CONSULTE LA PAPELERA DE RECICLAJE

DROP TABLE NOTAS_NEW;

SELECT * FROM RECYCLEBIN;  

-- Debido a que la papelera esta desactivada, no es posible recuperar la tabla.

------------------------------------------------------------------------------
--- MANEJO DE 2 VERSIONES ELIMINADAS DE UNA TABLA
------------------------------------------------------------------------------

--- 12. ACTIVAR LA PAPELERA DE RECICLAJE

ALTER SESSION SET RECYCLEBIN=ON;


--- 13. ELIMINAR LA TABLA “NOTAS”

DROP TABLE NOTAS;

--- 14. CONSULTAR LA PAPELERA DE RECICLAJE

SELECT * FROM RECYCLEBIN;

--- 15. CREAR UNA NUEVA TABLA “NOTAS”

CREATE TABLE NOTAS AS SELECT * FROM hr.DEPARTMENTS;

SELECT * FROM NOTAS;

--- 16. ELIMINAR LA TABLA “NOTAS”

DROP TABLE NOTAS;

SELECT * FROM RECYCLEBIN;

-- Se puede apreciar 2 elementos eliminados, consultemos cada versión

--- 17. RECUPERAR LAS TABLAS DROPEADAS

FLASHBACK TABLE "BIN$tjIjSWtvQdCvOW1at9OYFQ==$0" TO BEFORE DROP
RENAME TO NOTAS01;

FLASHBACK TABLE "BIN$hUZQXX1+Tt+UhjVfjch+Xw==$0" TO BEFORE DROP
RENAME TO NOTAS02;

SELECT * FROM NOTAS01
SELECT * FROM NOTAS02

/*                                        FLASHBACK VERSION QUERY
Usted puede utilizar Flashback Version Query para recuperar la historia de una fila. La característica de Flashback Query 
versión permite utilizar la cláusula VERSIONES para recuperar todas las versiones de las filas que hay entre dos puntos en el tiempo o dos SCN.
 */
 
CREATE TABLE CURSO ( id integer, curso char(50), costo integer, FECHA DATE DEFAULT SYSDATE );
-- CAMBIO 1
INSERT INTO CURSO VALUES ( 1 , 'ORACLE' , 350, SYSDATE ); 
COMMIT;

-- CAMBIO 2
UPDATE CURSO SET COSTO = 400 ,  FECHA = SYSDATE WHERE ID = 1 ; 
COMMIT;

-- CAMBIO 3
UPDATE CURSO SET CURSO  = 'ORACLE INICIAL',  FECHA = SYSDATE WHERE ID = 1 ; 
COMMIT;

-- CAMBIO 4
DELETE  CURSO WHERE ID = 1 ; 
COMMIT;

-- CAMBIO 5
INSERT INTO CURSO VALUES ( 2 , 'SQL' , 200, SYSDATE ); 
COMMIT;

-- MOSTRANDO RESULTADOS FINALES
SELECT * FROM CURSO;

-- MOSTRANDO TODAS LAS VERSIONES DE LAS FILAS
SELECT versions_xid , ID, CURSO, COSTO , FECHA FROM CURSO VERSIONS BETWEEN TIMESTAMP MINVALUE AND MAXVALUE
WHERE ID = 1;

/*                                                         FLASHBACK TABLE
Usando Flashback Table, se puede recuperar un conjunto de tablas a un punto específico en el tiempo sin necesidad de realizar 
operaciones de recuperación de punto en el tiempo tradicionales. */

CREATE TABLE ARTICULO  (ID  NUMBER(10) , NOMBRE CHAR(50) );
  
ALTER TABLE ARTICULO  ENABLE ROW MOVEMENT;

SELECT CURRENT_SCN FROM V$DATABASE; -- 2929250
SELECT SYSDATE FROM DUAL; --30/8/2025 20:46:18

INSERT INTO ARTICULO   VALUES (100 , 'QUESOS' );
COMMIT;
SELECT CURRENT_SCN FROM V$DATABASE; -- 2929358
SELECT SYSDATE FROM DUAL; --30/8/2025 20:46:52
  
INSERT INTO ARTICULO   VALUES (200 , 'FIDEOS' );
COMMIT;
SELECT CURRENT_SCN FROM V$DATABASE; -- 2929375
SELECT SYSDATE FROM DUAL;

INSERT INTO ARTICULO   VALUES (300 , 'LICORES' );
COMMIT;
SELECT CURRENT_SCN FROM V$DATABASE; -- 2929171
SELECT SYSDATE FROM DUAL;

SELECT * FROM ARTICULO ;

-- RESTAURANDO  
FLASHBACK TABLE ARTICULO   TO SCN 2929358;
SELECT * FROM ARTICULO  ;

FLASHBACK TABLE ARTICULO   
TO TIMESTAMP TO_TIMESTAMP('30/08/2025 20:46:18', 'DD-MM-YYYY HH24:MI:SS');

